language: node_js
node_js:
- 8
install:
- yarn install
before_install:
- npm install -g codecov
script:
- yarn pretest
- yarn test:es5:bs
- lerna run remap-coverage
after_success:
- codecov
after_failure:
- codecov
env:
  global:
  - secure: XTvVU38nJi2gCpeDo94TOqR8qpLu2BH3usjYcBvgtsvztPgZv8Zsq6fZiJXsrp7tt2cx/U8eJE0kGjYgmA56LQ4G7pNQeWkTVdxL/Ay+weu3DJI/FfJKJYuRFdyrCAgvV/O8WV8EXfk3N+5sUgSewGncvue4YhgdcCDnCoQF2ALLz9CKuKy2hrDMRBu3TLHUgcaaqWZnRKW0ZLdt/Le3qP7JIsYS4FAryc2Axm/FBl2FVd/XzTc4latj8jx0qy3tGACPIkTMGkQX1osa8zzgfXzqZRwnux7KtsmY0MDorUxBTAu4RuZfUVhbRBxGmuzXW0DgrmrHSA2ENWYhPJ1ivRBTOlSzBAHqr/9G6ZqjK3pE1edx01Q9WM1yc1c3Wc1TeplMVpI5mPcY/bRyCTtbubQX67yNVHMRcXc1oZA1TPBP6AGZavA+Sc88yzoeO38EjPcdR21HDmpasxd88o4X5mf0imp2f6N4sXFkfMjw2QcyYlSBdjb4b0z4PSS0olBFzd2E25BU3957x3psvOD9H5azs3Tmb9ep5L3WVPhJnxnpkegnfbnvt/Nvoy1rFx6Q6pKjt6sgac287r4R2voBlmASlej0Qk3LnHzhWFHgnu6fqg9VKGfIwPoAdaYp74f9Ll1umY3KSFUxP/p8vncqQaydcuUQAgb1Z0d7Uf3tlRg=
  - secure: fwSIJZqIcPg2i+GEETO+jzbvDCeqU8GGbx7vI2Ex+d/xZA/aTdNxrmedHkviW1DimzomtHQtup+1JeSX1nCgg2/FqKah8TWlf+z7LlWOuX9TB3KTOrrk4i+peDGNxcCJznf7Q1eDRc06tknVnBZncY3MECcEEstc1jhYpKRKEc8vHN3lz+Mx4A0S+XzBECbxf90wbsAAKI4nE22z2n1aDe1eawmN2Tw2+aRHD6zvlc6ciCrCXKRmfaK4LkR3vZX7MlfA3AxfTTHTTGYeqqu5NRY7Pvwf4GNt7+N0bqc9+mi1uP5Lt6lfTzsjd/d0B7aRwa7kveLAeVVporgHewmdOb8LegA5W4oKwTYMsut33MWQTLQ/r/SId9J1s1Ur62IZsFSuDm7LJ7z48hcfKXkXAPGNLu8LThQiLTb/4jpyDz31gxdLRxqK2CBp/yx3ve03VujPeHHOjETgz5WpSz86nHjLDyR/hvxZgFk9ltxaK8CDgH76oAEuAUvTo+K/kJDe4iTQ3b4eHQvtOS29y9tsTQUNI5pd/uvAATs7IXLjEqcjONZg984c8wbPlIzmQWctttC85dxZTXYJY63Ifjc2q14YKYH+vJ8CBMtBWFwtgAhgPF1nwYyeCDizvzSxYA6Si93jdCBRAMMp2hkRTtS2ePa0LHh/UOTDysNQm09inrc=
