import '@openlayers-elements/core/ol-map'
import '@polymer/iron-demo-helpers/demo-snippet'
import '@openlayers-elements/maps/ol-control'
import '@openlayers-elements/maps/ol-select'
import '@openlayers-elements/maps/ol-layer-wkt'
