import '@openlayers-elements/core/ol-map'
import '@openlayers-elements/swisstopo/swisstopo-wmts'
import '@polymer/iron-demo-helpers/demo-snippet'
import '@openlayers-elements/maps/ol-layer-openstreetmap'
import '@openlayers-elements/core/ol-layer-vector'
import '@openlayers-elements/maps/ol-marker-icon'
