import '@polymer/iron-demo-helpers/demo-pages-shared-styles'

import '@openlayers-elements/maps/ol-layer-openstreetmap'
import '@openlayers-elements/maps/ol-layer-wkt'
import '@openlayers-elements/maps/ol-layer-geojson'
import '@openlayers-elements/maps/ol-select'
import '@openlayers-elements/maps/ol-overlay'
import '@openlayers-elements/maps/ol-control'
import '@openlayers-elements/maps/ol-layer-xyz'
import '@openlayers-elements/core/ol-layer-vector'
import '@openlayers-elements/maps/ol-marker-icon'
import '@openlayers-elements/swisstopo/swisstopo-wmts'
import '@openlayers-elements/swisstopo/swisstopo-reprojected'
